package com.ojhdtapp.parabox.domain.model

data class Country(
    val name: String,
    val code: String, // like "+244"
    val flag: String  // like "🇦🇴"
) {
    companion object {
        val countryList = listOf(
            Country("Afghanistan", "+93", "🇦🇫"),
            Country("Albania", "+355", "🇦🇱"),
            Country("Algeria", "+213", "🇩🇿"),
            Country("American Samoa", "+1-684", "🇦🇸"),
            Country("Andorra", "+376", "🇦🇩"),
            Country("Angola", "+244", "🇦🇴"),
            Country("Anguilla", "+1-264", "🇦🇮"),
            Country("Antigua and Barbuda", "+1-268", "🇦🇬"),
            Country("Argentina", "+54", "🇦🇷"),
            Country("Armenia", "+374", "🇦🇲"),
            Country("Aruba", "+297", "🇦🇼"),
            Country("Australia", "+61", "🇦🇺"),
            Country("Austria", "+43", "🇦🇹"),
            Country("Azerbaijan", "+994", "🇦🇿"),
            Country("Bahamas", "+1-242", "🇧🇸"),
            Country("Bahrain", "+973", "🇧🇭"),
            Country("Bangladesh", "+880", "🇧🇩"),
            Country("Barbados", "+1-246", "🇧🇧"),
            Country("Belarus", "+375", "🇧🇾"),
            Country("Belgium", "+32", "🇧🇪"),
            Country("Belize", "+501", "🇧🇿"),
            Country("Benin", "+229", "🇧🇯"),
            Country("Bermuda", "+1-441", "🇧🇲"),
            Country("Bhutan", "+975", "🇧🇹"),
            Country("Bolivia, Plurinational State of", "+591", "🇧🇴"),
            Country("Bosnia and Herzegovina", "+387", "🇧🇦"),
            Country("Botswana", "+267", "🇧🇼"),
            Country("Brazil", "+55", "🇧🇷"),
            Country("British Indian Ocean Territory", "+246", "🇮🇴"),
            Country("Brunei Darussalam", "+673", "🇧🇳"),
            Country("Bulgaria", "+359", "🇧🇬"),
            Country("Burkina Faso", "+226", "🇧🇫"),
            Country("Burundi", "+257", "🇧🇮"),
            Country("Cabo Verde", "+238", "🇨🇻"),
            Country("Cambodia", "+855", "🇰🇭"),
            Country("Cameroon", "+237", "🇨🇲"),
            Country("Canada", "+1", "🇨🇦"),
            Country("Cayman Islands", "+1-345", "🇰🇾"),
            Country("Central African Republic", "+236", "🇨🇫"),
            Country("Chad", "+235", "🇹🇩"),
            Country("Chile", "+56", "🇨🇱"),
            Country("China", "+86", "🇨🇳"),
            Country("Christmas Island", "+61", "🇨🇽"),
            Country("Cocos (Keeling) Islands", "+61", "🇨🇨"),
            Country("Colombia", "+57", "🇨🇴"),
            Country("Comoros", "+269", "🇰🇲"),
            Country("Congo", "+242", "🇨🇬"),
            Country("Congo, The Democratic Republic of the", "+243", "🇨🇩"),
            Country("Cook Islands", "+682", "🇨🇰"),
            Country("Costa Rica", "+506", "🇨🇷"),
            Country("Croatia", "+385", "🇭🇷"),
            Country("Cuba", "+53", "🇨🇺"),
            Country("Curaçao", "+599", "🇨🇼"),
            Country("Cyprus", "+357", "🇨🇾"),
            Country("Czechia", "+420", "🇨🇿"),
            Country("Côte d'Ivoire", "+225", "🇨🇮"),
            Country("Denmark", "+45", "🇩🇰"),
            Country("Djibouti", "+253", "🇩🇯"),
            Country("Dominica", "+1-767", "🇩🇲"),
            Country("Dominican Republic", "+1-809", "🇩🇴"),
            Country("Ecuador", "+593", "🇪🇨"),
            Country("Egypt", "+20", "🇪🇬"),
            Country("El Salvador", "+503", "🇸🇻"),
            Country("Equatorial Guinea", "+240", "🇬🇶"),
            Country("Eritrea", "+291", "🇪🇷"),
            Country("Estonia", "+372", "🇪🇪"),
            Country("Eswatini", "+268", "🇸🇿"),
            Country("Ethiopia", "+251", "🇪🇹"),
            Country("Falkland Islands (Malvinas)", "+500", "🇫🇰"),
            Country("Faroe Islands", "+298", "🇫🇴"),
            Country("Fiji", "+679", "🇫🇯"),
            Country("Finland", "+358", "🇫🇮"),
            Country("France", "+33", "🇫🇷"),
            Country("French Guiana", "+594", "🇬🇫"),
            Country("French Polynesia", "+689", "🇵🇫"),
            Country("Gabon", "+241", "🇬🇦"),
            Country("Gambia", "+220", "🇬🇲"),
            Country("Georgia", "+995", "🇬🇪"),
            Country("Germany", "+49", "🇩🇪"),
            Country("Ghana", "+233", "🇬🇭"),
            Country("Gibraltar", "+350", "🇬🇮"),
            Country("Greece", "+30", "🇬🇷"),
            Country("Greenland", "+299", "🇬🇱"),
            Country("Grenada", "+1-473", "🇬🇩"),
            Country("Guadeloupe", "+590", "🇬🇵"),
            Country("Guam", "+1-671", "🇬🇺"),
            Country("Guatemala", "+502", "🇬🇹"),
            Country("Guinea", "+224", "🇬🇳"),
            Country("Guinea-Bissau", "+245", "🇬🇼"),
            Country("Guyana", "+592", "🇬🇾"),
            Country("Haiti", "+509", "🇭🇹"),
            Country("Holy See (Vatican City State)", "+379", "🇻🇦"),
            Country("Honduras", "+504", "🇭🇳"),
            Country("Hong Kong", "+852", "🇭🇰"),
            Country("Hungary", "+36", "🇭🇺"),
            Country("Iceland", "+354", "🇮🇸"),
            Country("India", "+91", "🇮🇳"),
            Country("Indonesia", "+62", "🇮🇩"),
            Country("Iran, Islamic Republic of", "+98", "🇮🇷"),
            Country("Iraq", "+964", "🇮🇶"),
            Country("Ireland", "+353", "🇮🇪"),
            Country("Israel", "+972", "🇮🇱"),
            Country("Italy", "+39", "🇮🇹"),
            Country("Jamaica", "+1-876", "🇯🇲"),
            Country("Japan", "+81", "🇯🇵"),
            Country("Jordan", "+962", "🇯🇴"),
            Country("Kazakhstan", "+7", "🇰🇿"),
            Country("Kenya", "+254", "🇰🇪"),
            Country("Kiribati", "+686", "🇰🇮"),
            Country("Korea, Democratic People's Republic of", "+850", "🇰🇵"),
            Country("Korea, Republic of", "+82", "🇰🇷"),
            Country("Kuwait", "+965", "🇰🇼"),
            Country("Kyrgyzstan", "+996", "🇰🇬"),
            Country("Lao People's Democratic Republic", "+856", "🇱🇦"),
            Country("Latvia", "+371", "🇱🇻"),
            Country("Lebanon", "+961", "🇱🇧"),
            Country("Lesotho", "+266", "🇱🇸"),
            Country("Liberia", "+231", "🇱🇷"),
            Country("Libya", "+218", "🇱🇾"),
            Country("Liechtenstein", "+423", "🇱🇮"),
            Country("Lithuania", "+370", "🇱🇹"),
            Country("Luxembourg", "+352", "🇱🇺"),
            Country("Macao", "+853", "🇲🇴"),
            Country("Madagascar", "+261", "🇲🇬"),
            Country("Malawi", "+265", "🇲🇼"),
            Country("Malaysia", "+60", "🇲🇾"),
            Country("Maldives", "+960", "🇲🇻"),
            Country("Mali", "+223", "🇲🇱"),
            Country("Malta", "+356", "🇲🇹"),
            Country("Marshall Islands", "+692", "🇲🇭"),
            Country("Martinique", "+596", "🇲🇶"),
            Country("Mauritania", "+222", "🇲🇷"),
            Country("Mauritius", "+230", "🇲🇺"),
            Country("Mayotte", "+262", "🇾🇹"),
            Country("Mexico", "+52", "🇲🇽"),
            Country("Micronesia, Federated States of", "+691", "🇫🇲"),
            Country("Moldova, Republic of", "+373", "🇲🇩"),
            Country("Monaco", "+377", "🇲🇨"),
            Country("Mongolia", "+976", "🇲🇳"),
            Country("Montenegro", "+382", "🇲🇪"),
            Country("Montserrat", "+1-664", "🇲🇸"),
            Country("Morocco", "+212", "🇲🇦"),
            Country("Mozambique", "+258", "🇲🇿"),
            Country("Myanmar", "+95", "🇲🇲"),
            Country("Namibia", "+264", "🇳🇦"),
            Country("Nauru", "+674", "🇳🇷"),
            Country("Nepal", "+977", "🇳🇵"),
            Country("Netherlands", "+31", "🇳🇱"),
            Country("New Caledonia", "+687", "🇳🇨"),
            Country("New Zealand", "+64", "🇳🇿"),
            Country("Nicaragua", "+505", "🇳🇮"),
            Country("Niger", "+227", "🇳🇪"),
            Country("Nigeria", "+234", "🇳🇬"),
            Country("Niue", "+683", "🇳🇺"),
            Country("North Macedonia", "+389", "🇲🇰"),
            Country("Norway", "+47", "🇳🇴"),
            Country("Oman", "+968", "🇴🇲"),
            Country("Pakistan", "+92", "🇵🇰"),
            Country("Palau", "+680", "🇵🇼"),
            Country("Palestine, State of", "+970", "🇵🇸"),
            Country("Panama", "+507", "🇵🇦"),
            Country("Papua New Guinea", "+675", "🇵🇬"),
            Country("Paraguay", "+595", "🇵🇾"),
            Country("Peru", "+51", "🇵🇪"),
            Country("Philippines", "+63", "🇵🇭"),
            Country("Poland", "+48", "🇵🇱"),
            Country("Portugal", "+351", "🇵🇹"),
            Country("Puerto Rico", "+1-787", "🇵🇷"),
            Country("Qatar", "+974", "🇶🇦"),
            Country("Romania", "+40", "🇷🇴"),
            Country("Russian Federation", "+7", "🇷🇺"),
            Country("Rwanda", "+250", "🇷🇼"),
            Country("Réunion", "+262", "🇷🇪"),
            Country("Saint Kitts and Nevis", "+1-869", "🇰🇳"),
            Country("Saint Lucia", "+1-758", "🇱🇨"),
            Country("Saint Martin (French part)", "+590", "🇲🇫"),
            Country("Saint Vincent and the Grenadines", "+1-784", "🇻🇨"),
            Country("Samoa", "+685", "🇼🇸"),
            Country("San Marino", "+378", "🇸🇲"),
            Country("Sao Tome and Principe", "+239", "🇸🇹"),
            Country("Saudi Arabia", "+966", "🇸🇦"),
            Country("Senegal", "+221", "🇸🇳"),
            Country("Serbia", "+381", "🇷🇸"),
            Country("Seychelles", "+248", "🇸🇨"),
            Country("Sierra Leone", "+232", "🇸🇱"),
            Country("Singapore", "+65", "🇸🇬"),
            Country("Sint Maarten (Dutch part)", "+1-721", "🇸🇽"),
            Country("Slovakia", "+421", "🇸🇰"),
            Country("Slovenia", "+386", "🇸🇮"),
            Country("Solomon Islands", "+677", "🇸🇧"),
            Country("Somalia", "+252", "🇸🇴"),
            Country("South Africa", "+27", "🇿🇦"),
            Country("South Sudan", "+211", "🇸🇸"),
            Country("Spain", "+34", "🇪🇸"),
            Country("Sri Lanka", "+94", "🇱🇰"),
            Country("Sudan", "+249", "🇸🇩"),
            Country("Suriname", "+597", "🇸🇷"),
            Country("Sweden", "+46", "🇸🇪"),
            Country("Switzerland", "+41", "🇨🇭"),
            Country("Syrian Arab Republic", "+963", "🇸🇾"),
            Country("Taiwan, Province of China", "+886", "🇹🇼"),
            Country("Tajikistan", "+992", "🇹🇯"),
            Country("Tanzania, United Republic of", "+255", "🇹🇿"),
            Country("Thailand", "+66", "🇹🇭"),
            Country("Timor-Leste", "+670", "🇹🇱"),
            Country("Togo", "+228", "🇹🇬"),
            Country("Tonga", "+676", "🇹🇴"),
            Country("Trinidad and Tobago", "+1-868", "🇹🇹"),
            Country("Tunisia", "+216", "🇹🇳"),
            Country("Turkey", "+90", "🇹🇷"),
            Country("Turkmenistan", "+993", "🇹🇲"),
            Country("Turks and Caicos Islands", "+1-649", "🇹🇨"),
            Country("Tuvalu", "+688", "🇹🇻"),
            Country("Uganda", "+256", "🇺🇬"),
            Country("Ukraine", "+380", "🇺🇦"),
            Country("United Arab Emirates", "+971", "🇦🇪"),
            Country("United Kingdom", "+44", "🇬🇧"),
            Country("United States", "+1", "🇺🇸"),
            Country("Uruguay", "+598", "🇺🇾"),
            Country("Uzbekistan", "+998", "🇺🇿"),
            Country("Vanuatu", "+678", "🇻🇺"),
            Country("Venezuela, Bolivarian Republic of", "+58", "🇻🇪"),
            Country("Viet Nam", "+84", "🇻🇳"),
            Country("Virgin Islands, British", "+1-284", "🇻🇬"),
            Country("Virgin Islands, U.S.", "+1-340", "🇻🇮"),
            Country("Yemen", "+967", "🇾🇪"),
            Country("Zambia", "+260", "🇿🇲"),
            Country("Zimbabwe", "+263", "🇿🇼"),
        )
    }
}
